//! # Morpheus Compiler
//!
//! Compiles AI-generated Rust code to WASM modules for safe hot-loading.
//!
//! ## The Core Safety Mechanism
//!
//! This is where Morpheus differs from TypeScript/JavaScript:
//! AI-generated code MUST compile and type-check before it can run.
//!
//! ```rust,ignore
//! use morpheus_compiler::{Compiler, SubprocessCompiler};
//!
//! let compiler = SubprocessCompiler::new().await?;
//! let ai_code = ai.generate("Add dark mode toggle").await?;
//!
//! match compiler.compile(&ai_code).await {
//!     Ok(wasm) => {
//!         // Type-checked! Safe to load.
//!         app.hot_reload(wasm)?;
//!     }
//!     Err(errors) => {
//!         // App still works! Show errors to user and AI.
//!         show_user("AI made a mistake: {}", errors);
//!         ai.fix_errors(&ai_code, errors).await?;
//!     }
//! }
//! ```

use morpheus_core::errors::Result;
use async_trait::async_trait;

pub mod subprocess;

pub use subprocess::SubprocessCompiler;

/// Result of compilation including both WASM binary and JavaScript glue code.
#[derive(Debug, Clone)]
pub struct CompilationResult {
    /// The compiled WASM binary.
    pub wasm_bytes: Vec<u8>,
    
    /// JavaScript glue code generated by wasm-bindgen.
    /// This is required to load and interact with the WASM module.
    pub js_glue: String,
}

/// A compiler that can turn Rust code into WASM modules.
#[async_trait]
pub trait Compiler {
    /// Compile Rust source code to a WASM module.
    ///
    /// Returns both the compiled WASM bytes and JavaScript glue code.
    async fn compile(&self, source: &str) -> Result<CompilationResult>;

    /// Check if source code type-checks without generating WASM.
    ///
    /// Faster than full compilation for quick validation.
    async fn check(&self, source: &str) -> Result<()>;
}

/// Compilation errors with source locations.
#[derive(Debug, Clone)]
pub struct CompilationError {
    /// Error message from rustc.
    pub message: String,

    /// File path (if available).
    pub file: Option<String>,

    /// Line number (1-indexed).
    pub line: Option<usize>,

    /// Column number (1-indexed).
    pub column: Option<usize>,

    /// Severity (error, warning, note).
    pub severity: Severity,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
    Note,
}
