//! Dynamic component traits and types.
//!
//! Components in Morpheus can be loaded, unloaded, and hot-reloaded at runtime.

use crate::permissions::Permissions;
use serde::{Deserialize, Serialize};

/// A component that can be dynamically loaded and hot-reloaded.
///
/// Unlike traditional frameworks where components are bundled at build time,
/// Morpheus components are WASM modules that can be loaded at runtime,
/// potentially generated by AI agents.
pub trait DynamicComponent {
    /// The type of messages this component can handle.
    type Message: Serialize + for<'de> Deserialize<'de>;

    /// The component's state type.
    ///
    /// Must be serializable for hot-reload and rollback.
    type State: Serialize + for<'de> Deserialize<'de>;

    /// Initialize component from saved state (for hot-reload).
    fn from_state(state: Self::State) -> Self;

    /// Render the component.
    ///
    /// Returns a view description that can be rendered to DOM.
    fn view(&self) -> View;

    /// Update component state in response to a message.
    fn update(&mut self, msg: Self::Message);

    /// Extract current state (for hot-reload/rollback).
    fn to_state(&self) -> Self::State;

    /// Declare what permissions this component needs.
    ///
    /// AI-generated components get minimal permissions by default.
    fn permissions(&self) -> Permissions {
        Permissions::default()
    }

    /// Called when component is first loaded.
    fn on_load(&mut self) {}

    /// Called when component is about to be unloaded.
    fn on_unload(&mut self) {}
}

/// A view that can be rendered.
///
/// Placeholder for now - will be designed based on what works best
/// for both static and AI-generated components.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum View {
    Element {
        tag: String,
        attrs: Vec<(String, String)>,
        children: Vec<View>,
    },
    Text(String),
}

/// Unique identifier for a component instance.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ComponentId(pub u64);

impl std::fmt::Display for ComponentId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:016x}", self.0)
    }
}

/// Metadata about a component.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComponentMetadata {
    /// Unique identifier.
    pub id: ComponentId,

    /// Human-readable name.
    pub name: String,

    /// Version (for tracking updates).
    pub version: u32,

    /// When this component was loaded.
    pub loaded_at: String,  // ISO 8601 timestamp

    /// Whether this component was AI-generated.
    pub ai_generated: bool,
}
